### ISSUE TITLE
Is manual control for scaling ingredients broken?

### ISSUE THREAD

**Issue by skepickle** [lachholden/obsidian-recipe-view#17]
Obsidian: v1.4.16
Recipe view: 0.3.5

In a non-ingredients section, I am trying to use the syntax in the [documentation](https://obsidian-recipe-view.readthedocs.io/en/latest/usage/scaling.html) to make it so that "Scale recipe" will alter the numbers in the directions.

`<span data-qty-parse>180 grams</span>`

When I scale the recipe, the '180 grams', remains unchanged even though the ingredient section's amounts scale correctly. Am I doing something wrong here?

**Comment by lachholden** [comment]
Could you please upload the whole .md file? It shouldn't be broken.

**Comment by skepickle** [comment]
Here's a simple one for toast (teehee) with an optional step:

```
## Ingredients
- 1 slice of white bread
- 0.5 tsp. unsalted butter

## Directions

#### Basic steps
- Toast bread in toaster.
- Spread butter onto toast.

#### Optional Steps
Combine all ingredients in a medium bowl. Test <span data-qty-parse>180 grams</span>.

## Nutrition
Will give you fae-heart-attacks.
```

When I scale this, only the values in the Ingredients section will scale... the 180 grams remains static.

**Comment by skepickle** [comment]
btw, I love this plugin. It's _super_ useful!

**Comment by skepickle** [comment]
I will say this, if I don't put the instructions under the "####" header, it scales fine... weird huh?

**Comment by lachholden** [comment]
I've figured it out :) You've got a nonbreaking space between the `<span` and the `data-qty-parse>`, which breaks the HTML parsing. Just delete that and replace it with a regular space and you're golden :)

**Comment by Eonflare14** [comment]
just to let you know the non breaking space seems to still be in the docs at https://obsidian-recipe-view.readthedocs.io/en/latest/usage/scaling.html
