### ISSUE TITLE
Can't mix fractions and decimals in quantity

### ISSUE THREAD

**Issue by benjamin-hodgson** [lachholden/obsidian-recipe-view#20]
Some of my recipes feature quantities which look something like this:

```
1.5 g (¼ tsp) vanilla paste
```

These quantities get scaled incorrectly. For example, when scaling by 3:

```
3 .15 g (¾ tsp) vanilla paste
```

<img width="231" alt="image" src="https://github.com/lachholden/obsidian-recipe-view/assets/3857587/e6fac9a0-d4fa-44e4-b95f-9055274d2c26">

Seems the `1.5` is getting tokenised as two quantities. As far as I can tell the bug appears to be [here](https://github.com/lachholden/obsidian-recipe-view/blob/26cffd5154070a1c2270e0f774b601356bc28cb5/src/quantities.ts#L25); `deUnicodeFractions` is returning `1 .5 g (1/4 tsp) vanilla paste`. The regex splits the string into `1` and `.5 g (1⁄4 tsp) vanilla paste`.

I think `.+` at the start of the second group is probably too permissive, since we don't expect to see inputs with anything other than numbers on either side of the fraction slash post-normalisation. I tried replacing it with `\d+` (to read `/(\d+)(\d+\u2044.+)\b/ig`) and it seemed to give me good results for all the inputs I could think of, but would defer to you on the desired behaviour.

Example with the proposed fix (after scaling by 3):

```
4.5 g (¾ tsp) vanilla paste
```
<img width="208" alt="image" src="https://github.com/lachholden/obsidian-recipe-view/assets/3857587/8ba0190d-6316-4441-ac38-fade832df2b5">

Thanks!

**Comment by lachholden** [comment]
Thanks for the detailed issue (and also for the coffee :))

I'm looking into this further now – the purpose of that regex was to help with mixed numbers that use unicode e.g. "1½", which I think would be broken by your proposed solution. It definitely needs to be made more specific though, working on that atm!

**Comment by lachholden** [comment]
Turns out NFKD normalisation is already converting fully to ASCII, so I've removed `deUnicodeFractions` entirely and will simply require there to be a space in mixed numbers. Going to write some tests and check everything still works
