### ISSUE TITLE
Problems with Evernote notes using designed templates

### ISSUE THREAD

**Issue by dbkmsu** [lachholden/obsidian-recipe-view#23]
After importing my notes from Evernote, I am trying to use the Obsidian Recipe plugin. When I toggle on the plugin, only the title of the note and any photos appear. All the text in tables (from the Evernote template) disappear. Any suggestions? Can I rid the notes of the tables when exporting from Evernote?

**Comment by lachholden** [comment]
Tables in the body text should just render as normal. At this stage, there is no support to list ingredients in tables (see #1), and there is no other special formatting or features that apply to tables. This sounds more like an issue with your Evernote export/template, which is not something I have any knowledge of.

Closing for now, if you have a particular example you can provide of a recipe that should render a certain way but isn't, then please get back to me. :)
