### ISSUE TITLE
Add tags to frontmatter wipes note

### ISSUE THREAD

**Issue by Fuzzyknurl** [lachholden/obsidian-recipe-view#27]
I was setting up a new folder for my recipes. I enter a few recipes manually and then I set up a template. After I set up the template and created a new note when I clicked the wisk to view the recipe in Recipe View the note went completely blank. It took me a while to figure out what was causing it. In my template, I added an empty tags property in the front matter. This caused the note to go blank. If I remove the tags property then everything works fine. I tried this a couple ways. If I create the recipe and then add an empty tags property, I can get it to happen. Clicking on the Recipe View icon causes the note to go blank. If I put in a tag it doesn't do it and if I remove the tag and it's empty again it does not go blank. But if I remove the tags property and add another empty tags property, it goes blank again.  
I hope this helps. I was frustrated for a while but then when I figured it out it felt good.

**Comment by lachsh** [comment]
Yeah there are some major bugs with the property handling at the moment which are next on my list to fix when I get the time! I need to make the plugin more forgiving.

This is related to #15 and #16. Currently, empty properties or properties having unexpected types (i.e. not a list, for `tags`) causes rendering to fail. If you go into source mode for properties, I imagine you would see that, although both appear empty in the UI, it would work for `tags: []` and not for `tags: `.
